<a href="/users/new">Добавить пользователя</a>
<form action="/users" method="get">
  <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
  <input type="submit" value="Найти!" />
</form>

<ul>
  <?php foreach ($users as $user): ?>
    <li><div><a href="/users/<?= htmlspecialchars($user['id']) ?>"><?= htmlspecialchars($user['name']) ?></a></div></li>
  <?php endforeach ?>
</ul>


<div>
<a href="?page=<?= $page < 2 ? 1 : $page - 1 ?>">Prev</a> <a href="?page=<?= $page + 1 ?>">Next</a>
</div>
